// Generated by scripts/build-cover-stickers.py from the cover-library prototype's
// sticker specimens. Do not edit: change gen_stickers.py there and re-run.
//
// Group defaults from the specimens: stroke #3A2E26, stroke-width 12, round caps and
// joins, on a 256 x 256 canvas. An element without `fill` has none; one without
// `stroke` inherits the group's ink.

export type StickerElement = {
  t: 'path' | 'circle' | 'ellipse' | 'rect' | 'polygon' | 'polyline' | 'line';
  d?: string;
  points?: string;
  cx?: number;
  cy?: number;
  r?: number;
  rx?: number;
  ry?: number;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  x1?: number;
  y1?: number;
  x2?: number;
  y2?: number;
  fill?: string;
  stroke?: string;
  sw?: number;
  opacity?: number;
  transform?: string;
};

export type CoverStickerSpec = {
  id: string;
  kind: 'face' | 'mark' | 'object';
  theme: string[];
  elements: StickerElement[];
};

export const STICKER_INK = '#3A2E26';
export const STICKER_CANVAS = 256;

export const COVER_STICKERS: CoverStickerSpec[] = [
  {"id":"face-grin","kind":"face","theme":["faces","social"],"elements":[{"t":"circle","cx":128,"cy":130,"r":102,"fill":"#F6CE72"},{"t":"circle","cx":92,"cy":112,"r":10,"fill":"#3A2E26","stroke":"none"},{"t":"circle","cx":164,"cy":112,"r":10,"fill":"#3A2E26","stroke":"none"},{"t":"path","d":"M80 158 Q128 206 176 158 Z","fill":"#FFF8F1"},{"t":"circle","cx":74,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"},{"t":"circle","cx":182,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"},
]},
  {"id":"face-love","kind":"face","theme":["faces","social"],"elements":[{"t":"circle","cx":128,"cy":130,"r":102,"fill":"#F6CE72"},{"t":"path","d":"M92 134 L70 112 Q62 100 74 94 Q84 90 92 100 Q100 90 110 94 Q122 100 114 112 Z","fill":"#F67673","sw":8},{"t":"path","d":"M164 134 L142 112 Q134 100 146 94 Q156 90 164 100 Q172 90 182 94 Q194 100 186 112 Z","fill":"#F67673","sw":8},{"t":"path","d":"M86 160 Q128 196 170 160","fill":"none"}]},
  {"id":"face-sweat","kind":"face","theme":["faces","social"],"elements":[{"t":"circle","cx":128,"cy":130,"r":102,"fill":"#F6CE72"},{"t":"circle","cx":92,"cy":114,"r":10,"fill":"#3A2E26","stroke":"none"},{"t":"circle","cx":164,"cy":114,"r":10,"fill":"#3A2E26","stroke":"none"},{"t":"path","d":"M92 170 Q128 184 164 166","fill":"none"},{"t":"path","d":"M206 58 Q232 96 206 110 Q180 96 206 58 Z","fill":"#8FD0F5","sw":10},{"t":"circle","cx":74,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"},{"t":"circle","cx":182,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"}]},
  {"id":"face-wink","kind":"face","theme":["faces","social"],"elements":[{"t":"circle","cx":128,"cy":130,"r":102,"fill":"#F6CE72"},{"t":"circle","cx":92,"cy":112,"r":10,"fill":"#3A2E26","stroke":"none"},{"t":"path","d":"M146 112 Q164 98 182 112","fill":"none","sw":10},{"t":"path","d":"M84 156 Q128 196 172 156","fill":"none"},{"t":"circle","cx":74,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"},{"t":"circle","cx":182,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"}]},
  {"id":"face-wow","kind":"face","theme":["faces","social"],"elements":[{"t":"circle","cx":128,"cy":130,"r":102,"fill":"#F6CE72"},{"t":"circle","cx":92,"cy":110,"r":12,"fill":"#3A2E26","stroke":"none"},{"t":"circle","cx":164,"cy":110,"r":12,"fill":"#3A2E26","stroke":"none"},{"t":"path","d":"M76 84 Q92 70 108 82","fill":"none","sw":10},{"t":"path","d":"M148 82 Q164 70 180 84","fill":"none","sw":10},{"t":"ellipse","cx":128,"cy":168,"rx":22,"ry":28,"fill":"#3A2E26","stroke":"none"},{"t":"circle","cx":74,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"},{"t":"circle","cx":182,"cy":156,"r":14,"fill":"#FFAA7A","stroke":"none"}]},
  {"id":"mark-arrow","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M40 184 Q70 60 196 86","fill":"none"},{"t":"path","d":"M160 60 L198 86 L172 124","fill":"none"}]},
  {"id":"mark-bang","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M70 40 L106 34 L104 152 L84 154 Z","fill":"none"},{"t":"circle","cx":92,"cy":202,"r":18,"fill":"none"},{"t":"path","d":"M150 34 L186 40 L172 154 L152 152 Z","fill":"none"},{"t":"circle","cx":164,"cy":202,"r":18,"fill":"none"}]},
  {"id":"mark-check","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M40 136 L104 196 L220 56","fill":"none"}]},
  {"id":"mark-circle","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M150 54 Q58 50 42 120 Q30 196 128 210 Q222 214 218 128 Q214 60 140 68 Q70 76 76 140","fill":"none"}]},
  {"id":"mark-heart","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M128 214 L50 134 Q22 100 48 70 Q80 42 112 70 L128 88 L144 70 Q176 42 208 70 Q234 100 206 134 Z","fill":"none"}]},
  {"id":"mark-sparkle","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M128 30 Q138 118 226 128 Q138 138 128 226 Q118 138 30 128 Q118 118 128 30 Z","fill":"none"}]},
  {"id":"mark-star","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M128 30 L154 98 L226 102 L170 148 L190 220 L128 180 L66 220 L86 148 L30 102 L102 98 Z","fill":"none"}]},
  {"id":"mark-wave","kind":"mark","theme":["marks"],"elements":[{"t":"path","d":"M28 134 Q52 100 76 134 Q100 168 124 134 Q148 100 172 134 Q196 168 220 134","fill":"none"},{"t":"path","d":"M44 184 Q68 160 92 184 Q116 208 140 184 Q164 160 188 184","fill":"none","sw":10}]},
  {"id":"obj-bag","kind":"object","theme":["shopping"],"elements":[{"t":"path","d":"M52 90 L204 90 L220 220 Q220 228 212 228 L44 228 Q36 228 36 220 Z","fill":"#F67673"},{"t":"path","d":"M92 90 L92 56 Q92 28 128 28 Q164 28 164 56 L164 90","fill":"none"}]},
  {"id":"obj-bike","kind":"object","theme":["transport"],"elements":[{"t":"circle","cx":68,"cy":166,"r":48,"fill":"none"},{"t":"circle","cx":188,"cy":166,"r":48,"fill":"none"},{"t":"path","d":"M68 166 L112 92 L172 92 L188 166 L112 166 Z","fill":"#F67673","sw":10},{"t":"path","d":"M100 76 L124 76 M164 76 L186 92","fill":"none","sw":10}]},
  {"id":"obj-cap","kind":"object","theme":["education"],"elements":[{"t":"path","d":"M128 54 L232 108 L128 162 L24 108 Z","fill":"#3A2E26"},{"t":"path","d":"M64 128 L64 174 Q128 220 192 174 L192 128","fill":"#A5E3AE"},{"t":"path","d":"M232 108 L232 170","fill":"none","sw":8},{"t":"circle","cx":232,"cy":184,"r":12,"fill":"#F67673","sw":8}]},
  {"id":"obj-coffee","kind":"object","theme":["food_drink"],"elements":[{"t":"path","d":"M44 110 L60 214 Q64 226 76 226 L156 226 Q168 226 172 214 L188 110 Z","fill":"#FFAA7A"},{"t":"path","d":"M188 128 Q232 128 226 164 Q220 192 180 188","fill":"none"},{"t":"path","d":"M44 110 L188 110","fill":"none"},{"t":"path","d":"M86 78 Q76 56 90 36 M116 78 Q106 56 120 36 M146 78 Q136 56 150 36","fill":"none","sw":8}]},
  {"id":"obj-coin","kind":"object","theme":["money"],"elements":[{"t":"circle","cx":128,"cy":128,"r":96,"fill":"#F6CE72"},{"t":"circle","cx":128,"cy":128,"r":64,"fill":"none","sw":8},{"t":"path","d":"M128 92 Q104 92 104 112 Q104 128 128 128 Q152 128 152 144 Q152 164 128 164","fill":"none","sw":10},{"t":"path","d":"M128 80 L128 176","fill":"none","sw":8}]},
  {"id":"obj-cross","kind":"object","theme":["health"],"elements":[{"t":"circle","cx":128,"cy":128,"r":100,"fill":"#FFF8F1"},{"t":"path","d":"M100 56 L156 56 L156 100 L200 100 L200 156 L156 156 L156 200 L100 200 L100 156 L56 156 L56 100 L100 100 Z","fill":"#F67673"}]},
  {"id":"obj-envelope","kind":"object","theme":["bureaucracy"],"elements":[{"t":"rect","x":30,"y":64,"width":196,"height":132,"rx":18,"fill":"#8FD0F5"},{"t":"path","d":"M30 80 L128 150 L226 80","fill":"none"},{"t":"path","d":"M30 196 L104 132","fill":"none","sw":8},{"t":"path","d":"M226 196 L152 132","fill":"none","sw":8}]},
  {"id":"obj-house","kind":"object","theme":["housing"],"elements":[{"t":"path","d":"M36 128 L128 44 L220 128","fill":"none"},{"t":"rect","x":60,"y":118,"width":136,"height":104,"rx":8,"fill":"#A5E3AE"},{"t":"rect","x":108,"y":156,"width":40,"height":66,"rx":8,"fill":"#F67673","sw":8},{"t":"rect","x":156,"y":60,"width":24,"height":40,"rx":4,"fill":"#3A2E26","stroke":"none"}]},
  {"id":"obj-key","kind":"object","theme":["housing"],"elements":[{"t":"circle","cx":84,"cy":96,"r":52,"fill":"#F6CE72"},{"t":"circle","cx":84,"cy":96,"r":16,"fill":"#FFF8F1","sw":8},{"t":"path","d":"M124 128 L212 216","fill":"none","sw":28},{"t":"path","d":"M124 128 L212 216","fill":"none","stroke":"#F6CE72","sw":10},{"t":"path","d":"M184 188 L206 166","fill":"none"},{"t":"path","d":"M160 164 L178 146","fill":"none"}]},
  {"id":"obj-lamp","kind":"object","theme":["brand"],"elements":[{"t":"path","d":"M128 36 Q56 36 56 108 Q56 150 92 176 L92 196 L164 196 L164 176 Q200 150 200 108 Q200 36 128 36 Z","fill":"#F6CE72"},{"t":"path","d":"M100 222 L156 222","fill":"none"},{"t":"path","d":"M24 60 L48 76 M232 60 L208 76","fill":"none","sw":10}]},
  {"id":"obj-people","kind":"object","theme":["social","brand"],"elements":[{"t":"circle","cx":128,"cy":128,"r":90,"fill":"none","sw":10},{"t":"circle","cx":128,"cy":40,"r":26,"fill":"#F67673"},{"t":"circle","cx":52,"cy":172,"r":26,"fill":"#8FD0F5"},{"t":"circle","cx":204,"cy":172,"r":26,"fill":"#F6CE72"}]},
  {"id":"obj-pin","kind":"object","theme":["places"],"elements":[{"t":"path","d":"M128 232 Q44 140 44 100 Q44 32 128 32 Q212 32 212 100 Q212 140 128 232 Z","fill":"#F67673"},{"t":"circle","cx":128,"cy":100,"r":30,"fill":"#FFF8F1","sw":8}]},
  {"id":"obj-pretzel","kind":"object","theme":["food_drink"],"elements":[{"t":"path","d":"M62 196 Q24 120 74 78 Q118 44 128 118 Q138 44 182 78 Q232 120 194 196 M62 196 Q104 236 128 182 Q152 236 194 196 M128 118 Q96 150 62 196 M128 118 Q160 150 194 196","fill":"none","sw":40},{"t":"path","d":"M62 196 Q24 120 74 78 Q118 44 128 118 Q138 44 182 78 Q232 120 194 196 M62 196 Q104 236 128 182 Q152 236 194 196 M128 118 Q96 150 62 196 M128 118 Q160 150 194 196","fill":"none","stroke":"#FFAA7A","sw":28}]},
  {"id":"obj-signpost","kind":"object","theme":["brand"],"elements":[{"t":"path","d":"M128 40 L128 232","fill":"none"},{"t":"path","d":"M128 60 L224 60 L244 86 L224 112 L128 112 Z","fill":"#F67673"},{"t":"path","d":"M128 128 L32 128 L12 154 L32 180 L128 180 Z","fill":"#8FD0F5"},{"t":"path","d":"M100 232 L156 232","fill":"none"}]},
  {"id":"obj-speech","kind":"object","theme":["language"],"elements":[{"t":"path","d":"M40 60 Q40 36 64 36 L192 36 Q216 36 216 60 L216 140 Q216 164 192 164 L112 164 L68 206 L76 164 L64 164 Q40 164 40 140 Z","fill":"#A5E3AE"},{"t":"circle","cx":88,"cy":100,"r":11,"fill":"#3A2E26","stroke":"none"},{"t":"circle","cx":128,"cy":100,"r":11,"fill":"#3A2E26","stroke":"none"},{"t":"circle","cx":168,"cy":100,"r":11,"fill":"#3A2E26","stroke":"none"}]},
  {"id":"obj-stamp","kind":"object","theme":["bureaucracy"],"elements":[{"t":"rect","x":106,"y":34,"width":44,"height":56,"rx":14,"fill":"#CDBBEF"},{"t":"rect","x":88,"y":90,"width":80,"height":40,"rx":12,"fill":"#CDBBEF"},{"t":"rect","x":40,"y":130,"width":176,"height":44,"rx":14,"fill":"#3A2E26"},{"t":"rect","x":56,"y":194,"width":144,"height":30,"rx":10,"fill":"#F67673","sw":8}]},
  {"id":"obj-ticket","kind":"object","theme":["culture"],"elements":[{"t":"path","d":"M36 72 L220 72 Q220 108 196 112 Q220 116 220 150 L36 150 Q36 116 60 112 Q36 108 36 72 Z","fill":"#CDBBEF"},{"t":"path","d":"M152 86 L152 136","fill":"none","sw":8},{"t":"path","d":"M60 196 L196 196","fill":"none","sw":8}]},
  {"id":"obj-tower","kind":"object","theme":["places","brand"],"elements":[{"t":"circle","cx":128,"cy":132,"r":100,"fill":"#8FD0F5"},{"t":"path","d":"M118 36 L138 36 L134 86 L122 86 Z","fill":"#3A2E26"},{"t":"circle","cx":128,"cy":118,"r":34,"fill":"#FFF8F1"},{"t":"path","d":"M112 152 L144 152 L158 226 L98 226 Z","fill":"#FFF8F1"},{"t":"path","d":"M100 170 L156 170","fill":"none","sw":8}]},
  {"id":"obj-tram","kind":"object","theme":["transport"],"elements":[{"t":"path","d":"M128 28 L104 56 M128 28 L152 56","fill":"none","sw":8},{"t":"rect","x":36,"y":56,"width":184,"height":128,"rx":26,"fill":"#F6CE72"},{"t":"rect","x":56,"y":80,"width":56,"height":44,"rx":10,"fill":"#8FD0F5","sw":8},{"t":"rect","x":144,"y":80,"width":56,"height":44,"rx":10,"fill":"#8FD0F5","sw":8},{"t":"circle","cx":80,"cy":206,"r":16,"fill":"#3A2E26"},{"t":"circle","cx":176,"cy":206,"r":16,"fill":"#3A2E26"},{"t":"path","d":"M60 150 L196 150","fill":"none","sw":8}]}];

export const COVER_STICKER_BY_ID: Record<string, CoverStickerSpec> = Object.fromEntries(
  COVER_STICKERS.map((s) => [s.id, s]),
);
