#!/usr/bin/env python3
"""Turn the drawn sticker specimens into data the app can render (D-164).

Reads every SVG in the cover-library prototype (outputs/cover-asset-library-prototype/stickers,
the set lint_stickers.py has approved) and writes lib/coverStickers.ts: one record per sticker
with its geometry as plain elements. react-native-svg draws them; the prototype's render modes
(puffy / die-cut / ink / crayon) are re-created in components/community/CoverSticker.tsx from the
same elements, so a sticker edited in gen_stickers.py reaches the app by re-running this.

Usage (from novaku-app/):
    python scripts/build-cover-stickers.py
"""
import json
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

HERE = Path(__file__).resolve().parent
SRC = HERE.parent.parent / "outputs" / "cover-asset-library-prototype" / "stickers"
OUT = HERE.parent / "lib" / "coverStickers.ts"
NS = "{http://www.w3.org/2000/svg}"
INK = "#3A2E26"

KEEP = {
    "path": ("d",),
    "circle": ("cx", "cy", "r"),
    "ellipse": ("cx", "cy", "rx", "ry"),
    "rect": ("x", "y", "width", "height", "rx", "ry"),
    "polygon": ("points",),
    "polyline": ("points",),
    "line": ("x1", "y1", "x2", "y2"),
}
STYLE = {"fill": "fill", "stroke": "stroke", "stroke-width": "sw", "opacity": "opacity", "transform": "transform"}


def num(value: str):
    try:
        f = float(value)
        return int(f) if f.is_integer() else f
    except ValueError:
        return value


def convert(path: Path) -> dict:
    root = ET.parse(path).getroot()
    desc = root.find(f"{NS}desc")
    meta = json.loads(desc.text) if desc is not None and desc.text else {}
    group = root.find(f"{NS}g")
    if group is None:
        raise SystemExit(f"{path.name}: no <g>")
    elements = []
    for node in group.iter():
        tag = node.tag.replace(NS, "")
        if tag not in KEEP:
            continue
        el: dict = {"t": tag}
        for attr in KEEP[tag]:
            if attr in node.attrib:
                el[attr] = node.attrib[attr] if attr in ("d", "points") else num(node.attrib[attr])
        for attr, key in STYLE.items():
            if attr in node.attrib:
                el[key] = num(node.attrib[attr]) if key in ("sw", "opacity") else node.attrib[attr]
        elements.append(el)
    return {
        "id": meta.get("id") or path.stem,
        "kind": meta.get("kind", "object"),
        "theme": meta.get("theme", []),
        "elements": elements,
    }


def main() -> int:
    files = sorted(SRC.glob("*.svg"))
    if not files:
        print(f"no stickers under {SRC}", file=sys.stderr)
        return 1
    stickers = [convert(f) for f in files]
    body = json.dumps(stickers, ensure_ascii=False, separators=(",", ":"))
    # One record per line keeps the diff readable when a single sticker changes.
    body = re.sub(r'\},\{"id"', '},\n  {"id"', body)
    body = body.replace('[{"id"', '[\n  {"id"', 1).replace("}]", "},\n]", 1)
    OUT.write_text(
        "// Generated by scripts/build-cover-stickers.py from the cover-library prototype's\n"
        "// sticker specimens. Do not edit: change gen_stickers.py there and re-run.\n"
        "//\n"
        f"// Group defaults from the specimens: stroke {INK}, stroke-width 12, round caps and\n"
        "// joins, on a 256 x 256 canvas. An element without `fill` has none; one without\n"
        "// `stroke` inherits the group's ink.\n\n"
        "export type StickerElement = {\n"
        "  t: 'path' | 'circle' | 'ellipse' | 'rect' | 'polygon' | 'polyline' | 'line';\n"
        "  d?: string;\n  points?: string;\n  cx?: number;\n  cy?: number;\n  r?: number;\n  rx?: number;\n  ry?: number;\n"
        "  x?: number;\n  y?: number;\n  width?: number;\n  height?: number;\n  x1?: number;\n  y1?: number;\n  x2?: number;\n  y2?: number;\n"
        "  fill?: string;\n  stroke?: string;\n  sw?: number;\n  opacity?: number;\n  transform?: string;\n};\n\n"
        "export type CoverStickerSpec = {\n  id: string;\n  kind: 'face' | 'mark' | 'object';\n  theme: string[];\n  elements: StickerElement[];\n};\n\n"
        f"export const STICKER_INK = '{INK}';\nexport const STICKER_CANVAS = 256;\n\n"
        f"export const COVER_STICKERS: CoverStickerSpec[] = {body};\n\n"
        "export const COVER_STICKER_BY_ID: Record<string, CoverStickerSpec> = Object.fromEntries(\n"
        "  COVER_STICKERS.map((s) => [s.id, s]),\n);\n",
        encoding="utf-8",
    )
    print(f"{len(stickers)} stickers -> {OUT.relative_to(HERE.parent)} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
