#!/usr/bin/env python3
"""Which codepoints each bundled cover face can draw (D-148 for the cover packs, D-164).

Reads the TTFs the cover packs register in app/_layout.tsx and writes lib/coverFontCoverage.ts:
one packed codepoint list per face, in the same base-36 delta encoding lib/displayFont.ts reads
for the display face. A title is set in a pack's face only when every glyph of it is in that
face's list; otherwise the whole title keeps the system stack. Never a mixture.

Usage (from novaku-app/):
    python scripts/build-cover-font-coverage.py
"""
from pathlib import Path

from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
FONTS = ROOT / "node_modules" / "@expo-google-fonts"
OUT = ROOT / "lib" / "coverFontCoverage.ts"

# family name registered with expo-font -> package file
FACES = {
    "Caveat_700Bold": "caveat/700Bold/Caveat_700Bold.ttf",
    "PatrickHand_400Regular": "patrick-hand/400Regular/PatrickHand_400Regular.ttf",
    "Kalam_700Bold": "kalam/700Bold/Kalam_700Bold.ttf",
    "PermanentMarker_400Regular": "permanent-marker/400Regular/PermanentMarker_400Regular.ttf",
    "RockSalt_400Regular": "rock-salt/400Regular/RockSalt_400Regular.ttf",
    "CoveredByYourGrace_400Regular": "covered-by-your-grace/400Regular/CoveredByYourGrace_400Regular.ttf",
    "AmaticSC_700Bold": "amatic-sc/700Bold/AmaticSC_700Bold.ttf",
    "PlayfairDisplay_800ExtraBold": "playfair-display/800ExtraBold/PlayfairDisplay_800ExtraBold.ttf",
    "Lobster_400Regular": "lobster/400Regular/Lobster_400Regular.ttf",
}


def packed(codepoints: list[int]) -> str:
    out = []
    previous = 0
    for cp in sorted(codepoints):
        out.append(base36(cp - previous))
        previous = cp
    return ".".join(out)


def base36(n: int) -> str:
    digits = "0123456789abcdefghijklmnopqrstuvwxyz"
    if n == 0:
        return "0"
    s = ""
    while n:
        n, r = divmod(n, 36)
        s = digits[r] + s
    return s


def main() -> int:
    lines = [
        "// Generated by scripts/build-cover-font-coverage.py. Do not edit.",
        "// Packed as base-36 deltas between sorted codepoints; lib/coverFonts.ts unpacks it.",
        "",
        "export const COVER_FONT_PACKED_COVERAGE: Record<string, string> = {",
    ]
    for family, rel in FACES.items():
        font = TTFont(FONTS / rel, lazy=True)
        cmap = font.getBestCmap()
        cps = [cp for cp in cmap if cp >= 0x20]
        lines.append(f"  {family}: '{packed(cps)}',")
        print(f"{family}: {len(cps)} codepoints")
    lines.append("};")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"-> {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
