#!/usr/bin/env python3
"""Subset Source Han Sans Bold down to something a phone can carry (D-148).

The cover has refused to set a fontFamily since it was written, for a measured
reason: Plus Jakarta Sans carries 721 codepoints and roughly 38 of the app's
106 locales would silently render as tofu. lisum has commercially licensed
fonts, and the useful one is Source Han Sans (SIL OFL, pan-CJK) -- but the
shipped Bold is 17 MB for one weight, which is more than the whole app.

So it is subset here, to exactly the coverage the gate in lib/displayFont.ts
then enforces at runtime:

  * ASCII, Latin-1 Supplement, Latin Extended-A  (German, French, Polish, ...)
  * General Punctuation and the quotes a cover actually prints
  * CJK symbols and punctuation, and the fullwidth forms
  * every hanzi in GB2312 -- 6763 of them, enumerated from the codec rather
    than from a frequency list somebody typed out, so the set is exact

Not included, and therefore never set in this face: Cyrillic, Greek, Arabic,
Thai, Devanagari, Hangul, kana. Those keep the system stack, which has them.

Run:  python scripts/build-display-font.py
Out:  assets/fonts/PosterviaDisplay-Bold.otf  +  lib/displayFontCoverage.ts
"""
import subprocess
import sys
from pathlib import Path

SOURCE = Path(r"E:\素材\字体\0-字体（可商用）\思源黑体\SourceHanSansSC-Bold.otf")
APP = Path(__file__).resolve().parents[1]
OUT_FONT = APP / "assets" / "fonts" / "PosterviaDisplay-Bold.otf"
OUT_TS = APP / "lib" / "displayFontCoverage.ts"

NEWLINE = chr(10)
QUOTE = chr(39)

# Ranges kept wholesale. Each is a (first, last) pair, inclusive.
RANGES = [
    (0x0020, 0x007E),  # ASCII
    (0x00A0, 0x00FF),  # Latin-1 Supplement
    (0x0100, 0x017F),  # Latin Extended-A
    (0x2010, 0x203A),  # General Punctuation: dashes, quotes, bullets
    (0x20AC, 0x20AC),  # euro
    (0x3000, 0x303F),  # CJK symbols and punctuation
    (0xFF00, 0xFF65),  # Fullwidth forms
]

ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"


def base36(value: int) -> str:
    if value == 0:
        return "0"
    out = ""
    while value:
        value, digit = divmod(value, 36)
        out = ALPHABET[digit] + out
    return out


def gb2312_hanzi() -> set[int]:
    """Every character GB2312 can encode, straight from the codec."""
    found: set[int] = set()
    for high in range(0xB0, 0xF8):
        for low in range(0xA1, 0xFF):
            try:
                ch = bytes([high, low]).decode("gb2312")
            except UnicodeDecodeError:
                continue
            found.add(ord(ch))
    return found


def main() -> None:
    if not SOURCE.exists():
        print(f"source font not found: {SOURCE}")
        sys.exit(1)

    codepoints = {cp for first, last in RANGES for cp in range(first, last + 1)}
    codepoints |= gb2312_hanzi()
    print(f"keeping {len(codepoints)} codepoints")

    OUT_FONT.parent.mkdir(parents=True, exist_ok=True)
    spec = APP / "scripts" / ".display-font-unicodes.txt"
    spec.write_text(",".join(f"U+{cp:04X}" for cp in sorted(codepoints)), encoding="utf-8")

    subprocess.run(
        [
            sys.executable, "-m", "fontTools.subset", str(SOURCE),
            f"--unicodes-file={spec}",
            f"--output-file={OUT_FONT}",
            # kern and liga only. Keeping vert/vrt2/locl and every name record
            # cost 1.6 MB for features this cover never asks for -- the vertical
            # layout stacks glyphs itself rather than calling for vertical forms.
            "--layout-features=kern,liga",
            "--drop-tables+=DSIG",
        ],
        check=True,
    )
    spec.unlink(missing_ok=True)
    print(f"{OUT_FONT.name}: {OUT_FONT.stat().st_size / 1024 / 1024:.2f} MB")

    # The runtime gate, delta-encoded in base 36 rather than emitted as ranges:
    # the kept hanzi are pinyin-ordered in GB2312, so their codepoints scatter
    # and collapse into ~3500 ranges -- 60 KB of source to answer a question a
    # 12 KB string answers. The app expands it to a Set once, at first use.
    previous = 0
    deltas = []
    for cp in sorted(codepoints):
        deltas.append(base36(cp - previous))
        previous = cp
    packed = ".".join(deltas)

    lines = [
        "// GENERATED by scripts/build-display-font.py - do not edit.",
        "// The exact coverage of assets/fonts/PosterviaDisplay-Bold.otf:",
        f"// {len(deltas)} codepoints, delta-encoded in base 36, dot separated.",
        "// Expanded once at first use by lib/displayFont.ts.",
        "",
        "export const DISPLAY_FONT_PACKED_COVERAGE =",
        "  " + QUOTE + packed + QUOTE + ";",
        "",
    ]
    OUT_TS.write_text(NEWLINE.join(lines), encoding="utf-8")
    print(f"wrote {OUT_TS.name}: {len(packed) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
